# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/afar/Modifing_Packets_On-The-Fly_In_SCAPY/evilpostman/gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setEnabled(True)
        self.tab_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab_widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab_widget.setMouseTracking(False)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setObjectName("tab_widget")
        self.start_tab = QtWidgets.QWidget()
        self.start_tab.setObjectName("start_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.start_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.start_tab_label_instruction = QtWidgets.QLabel(self.start_tab)
        self.start_tab_label_instruction.setMinimumSize(QtCore.QSize(0, 0))
        self.start_tab_label_instruction.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.start_tab_label_instruction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_tab_label_instruction.setWordWrap(True)
        self.start_tab_label_instruction.setObjectName("start_tab_label_instruction")
        self.gridLayout_6.addWidget(self.start_tab_label_instruction, 2, 0, 1, 1)
        self.start_tab_button_next = QtWidgets.QPushButton(self.start_tab)
        self.start_tab_button_next.setObjectName("start_tab_button_next")
        self.gridLayout_6.addWidget(self.start_tab_button_next, 3, 0, 1, 1)
        self.start_tab_label_title = QtWidgets.QLabel(self.start_tab)
        self.start_tab_label_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.start_tab_label_title.setObjectName("start_tab_label_title")
        self.gridLayout_6.addWidget(self.start_tab_label_title, 1, 0, 1, 1)
        self.tab_widget.addTab(self.start_tab, "")
        self.sniff_tab = QtWidgets.QWidget()
        self.sniff_tab.setObjectName("sniff_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.sniff_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.sniff_tab_button_create_filter_from_packet = QtWidgets.QPushButton(self.sniff_tab)
        self.sniff_tab_button_create_filter_from_packet.setObjectName("sniff_tab_button_create_filter_from_packet")
        self.gridLayout.addWidget(self.sniff_tab_button_create_filter_from_packet, 5, 1, 1, 1)
        self.sniff_tab_button_next = QtWidgets.QPushButton(self.sniff_tab)
        self.sniff_tab_button_next.setObjectName("sniff_tab_button_next")
        self.gridLayout.addWidget(self.sniff_tab_button_next, 5, 3, 1, 1)
        self.sniff_tab_button_sniff = QtWidgets.QPushButton(self.sniff_tab)
        self.sniff_tab_button_sniff.setObjectName("sniff_tab_button_sniff")
        self.gridLayout.addWidget(self.sniff_tab_button_sniff, 5, 2, 1, 1)
        self.sniff_tab_button_back = QtWidgets.QPushButton(self.sniff_tab)
        self.sniff_tab_button_back.setObjectName("sniff_tab_button_back")
        self.gridLayout.addWidget(self.sniff_tab_button_back, 5, 0, 1, 1)
        self.sniff_tab_packets_list = QtWidgets.QTableWidget(self.sniff_tab)
        self.sniff_tab_packets_list.setObjectName("sniff_tab_packets_list")
        self.sniff_tab_packets_list.setColumnCount(2)
        self.sniff_tab_packets_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sniff_tab_packets_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sniff_tab_packets_list.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.sniff_tab_packets_list, 1, 0, 1, 4)
        self.tab_widget.addTab(self.sniff_tab, "")
        self.filters_tab = QtWidgets.QWidget()
        self.filters_tab.setObjectName("filters_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.filters_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.filters_tab_button_next = QtWidgets.QPushButton(self.filters_tab)
        self.filters_tab_button_next.setObjectName("filters_tab_button_next")
        self.gridLayout_5.addWidget(self.filters_tab_button_next, 4, 2, 1, 1)
        self.filters_tab_button_create_filter = QtWidgets.QPushButton(self.filters_tab)
        self.filters_tab_button_create_filter.setObjectName("filters_tab_button_create_filter")
        self.gridLayout_5.addWidget(self.filters_tab_button_create_filter, 4, 1, 1, 1)
        self.filters_tab_button_back = QtWidgets.QPushButton(self.filters_tab)
        self.filters_tab_button_back.setObjectName("filters_tab_button_back")
        self.gridLayout_5.addWidget(self.filters_tab_button_back, 4, 0, 1, 1)
        self.filters_tab_list_of_packets = QtWidgets.QTableWidget(self.filters_tab)
        self.filters_tab_list_of_packets.setObjectName("filters_tab_list_of_packets")
        self.filters_tab_list_of_packets.setColumnCount(3)
        self.filters_tab_list_of_packets.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filters_tab_list_of_packets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filters_tab_list_of_packets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filters_tab_list_of_packets.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.filters_tab_list_of_packets, 0, 0, 1, 3)
        self.tab_widget.addTab(self.filters_tab, "")
        self.modified_tab = QtWidgets.QWidget()
        self.modified_tab.setObjectName("modified_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.modified_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modified_tab_button_show = QtWidgets.QPushButton(self.modified_tab)
        self.modified_tab_button_show.setObjectName("modified_tab_button_show")
        self.gridLayout_2.addWidget(self.modified_tab_button_show, 1, 1, 1, 1)
        self.modified_tab_back = QtWidgets.QPushButton(self.modified_tab)
        self.modified_tab_back.setObjectName("modified_tab_back")
        self.gridLayout_2.addWidget(self.modified_tab_back, 1, 0, 1, 1)
        self.modified_tab_button_stop = QtWidgets.QPushButton(self.modified_tab)
        self.modified_tab_button_stop.setObjectName("modified_tab_button_stop")
        self.gridLayout_2.addWidget(self.modified_tab_button_stop, 1, 2, 1, 1)
        self.modified_tab_list_of_packets = QtWidgets.QTableWidget(self.modified_tab)
        self.modified_tab_list_of_packets.setObjectName("modified_tab_list_of_packets")
        self.modified_tab_list_of_packets.setColumnCount(3)
        self.modified_tab_list_of_packets.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.modified_tab_list_of_packets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modified_tab_list_of_packets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.modified_tab_list_of_packets.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.modified_tab_list_of_packets, 0, 0, 1, 3)
        self.tab_widget.addTab(self.modified_tab, "")
        self.gridLayout_4.addWidget(self.tab_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionETHERNET = QtWidgets.QAction(MainWindow)
        self.actionETHERNET.setObjectName("actionETHERNET")
        self.actionWLAN = QtWidgets.QAction(MainWindow)
        self.actionWLAN.setObjectName("actionWLAN")
        self.actionFiltry = QtWidgets.QAction(MainWindow)
        self.actionFiltry.setObjectName("actionFiltry")

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(3)
        self.sniff_tab_button_sniff.clicked.connect(self.sniff_tab_button_sniff.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EvilPostman"))
        self.start_tab_label_instruction.setText(_translate("MainWindow", "<html><head/><body><p><br/><br/>Modyfikacja pakietów przebiega w nasŧępujący sposób: <br/>A) Metoda szybka:<br/>B) Metoda zaawansowana: <br/><br/>1) Przechodzimy dalej i włączamy przechwytywanie pakietów:<br/>2) Sposoby tworzeni a filtrów:</p><p>Metoda szybka: <br/>Klikamy prawym przyciskiem myszy na pakiecie i wybieramy utwórz szablon. Przechodzimy do wygenerowanego filtra i wybieramy wartości które mają zostać zmodyfikowane.<br/>Następnie akceptujemy zmiany i od tego momentu pakiety będą przechwytywane i modyfikowane.</p><p>Metoda zaawansowana: <br/>Klikamy na przycisk utwórz filtry<br/>Przechodzimy do wygenerowanego filtra i wybieramy wartości które mają zostać zmodyfikowane </p><p>Następnie akceptujemy zmiany i od tego momentu pakiety będą przechwytywane<br/>i modyfikowane.</p><p>4) Wysyłamy pakiet</p></body></html>"))
        self.start_tab_button_next.setText(_translate("MainWindow", "Dalej"))
        self.start_tab_label_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Tryb działania modyfikatora pakietów:</span></p></body></html>"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.start_tab), _translate("MainWindow", "Start"))
        self.sniff_tab_button_create_filter_from_packet.setText(_translate("MainWindow", "Utwórz filtr na podstawie pakietu"))
        self.sniff_tab_button_next.setText(_translate("MainWindow", "Dalej"))
        self.sniff_tab_button_sniff.setText(_translate("MainWindow", "Włącz przechwytywanie pakietów"))
        self.sniff_tab_button_back.setText(_translate("MainWindow", "Powrót"))
        item = self.sniff_tab_packets_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nr."))
        item = self.sniff_tab_packets_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Packet"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.sniff_tab), _translate("MainWindow", "Przechwytywanie"))
        self.filters_tab_button_next.setText(_translate("MainWindow", "Dalej"))
        self.filters_tab_button_create_filter.setText(_translate("MainWindow", "Utwórz filtr"))
        self.filters_tab_button_back.setText(_translate("MainWindow", "Powrót"))
        item = self.filters_tab_list_of_packets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nr."))
        item = self.filters_tab_list_of_packets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Filtr"))
        item = self.filters_tab_list_of_packets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Aktywny"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.filters_tab), _translate("MainWindow", "Filtry"))
        self.modified_tab_button_show.setText(_translate("MainWindow", "Pokaż pakiet"))
        self.modified_tab_back.setText(_translate("MainWindow", "powrót"))
        self.modified_tab_button_stop.setText(_translate("MainWindow", "Zatrzymaj działanie"))
        item = self.modified_tab_list_of_packets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nr."))
        item = self.modified_tab_list_of_packets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Filtr"))
        item = self.modified_tab_list_of_packets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Aktywny"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.modified_tab), _translate("MainWindow", "Lista zmodyfikwanych"))
        self.actionETHERNET.setText(_translate("MainWindow", "&Filtry"))
        self.actionWLAN.setText(_translate("MainWindow", "&Interfejsy"))
        self.actionFiltry.setText(_translate("MainWindow", "Filtry"))

